# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
group_by_frequency <- function(vardates, freq) {
    .Call(`_idates_group_by_frequency`, vardates, freq)
}

#' Helper function to calculate the day of the week (1 = Monday, ..., 7 = Sunday)
#' @export
day_of_week <- function(year, month, day) {
    .Call(`_idates_day_of_week`, year, month, day)
}

#' Calculation of day of the year
#' @export
day_of_year <- function(year, month, day) {
    .Call(`_idates_day_of_year`, year, month, day)
}

#' Calculate ISO week and year
#' @export
iso_week_and_year <- function(year, month, day) {
    .Call(`_idates_iso_week_and_year`, year, month, day)
}

